default_language_version:
  python: python3.12

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-merge-conflict
  - id: check-added-large-files
    args: ['--maxkb=2000']
- repo: https://github.com/codespell-project/codespell
  rev: "v2.4.1"
  hooks:
  - id: codespell
    name: codespell
    description: Checks for common misspellings in text files.
    entry: codespell
    language: python
    args: ['--skip=uv.lock']
- repo: https://github.com/pycqa/isort
  rev: 6.0.0
  hooks:
  - id: isort
    name: isort (python)
    args: ['--force-single-line-imports']
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 'v0.9.3'
  hooks:
  - id: ruff-format
    name: ruff formatter
  - id: ruff
    name: ruff linter
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.14.1'
  hooks:
  - id: mypy
    additional_dependencies:
    - types-requests
    - types-beautifulsoup4
- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: uv run pylint ./tests ./autoexpense3
    language: system
    types: [ python ]
