target-version = "py312"
line-length = 88
indent-width = 4

[format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
preview = true

[lint]
preview = true
select = ["ALL"]
ignore = [
    "D",  # pydocstyle
    "PT",  # pytest
    "SIM",  # simplify
    "PLR",  # pylint refactor
    "CPY",  # copyright
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

[lint.per-file-ignores]
"**/*_test.py" = [
    "S101",  # assert
]
