target-version = "py312"
line-length = 88
indent-width = 4

[format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
preview = true

[lint]
preview = true
select = ["ALL"]
ignore = [
    "D100",  # missing docstring in public module
    "D104",  # missing docstring in public package
    "D107",  # missing docstring in public init method
    "D203",  # missing 1 blank line before docstring
    "D204",  # missing 1 blank line after docstring
    "D213",  # multiline docstring should start on second line
    "DOC",  # pydoclint  Mostly arguments and return value annotation. Done with type annotation.
    "CPY",  # copyright presence
    "COM812",  # trailing comma. As suggested by ruff formatter command
    "FIX002",  # line contains TODO, consider resolving the issue
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

[lint.per-file-ignores]
"**/*_test.py" = [
    "S101",  # assert
    "D102",  # missing docstring in public method
    "D103",  # missing docstring in public function
]
