name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install dependencies
      run: |
        pip install uv
        uv run playwright install --with-deps

    - name: run tests
      run: uv run make test

    - name: Configure SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_FOR_LINODE}}

    - name: Deploy
      run: |
        cd ${{ github.workspace }}
        ssh-keyscan -t rsa ${{ vars.SSH_HOST }} >> ~/.ssh/known_hosts
        ssh ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} "cd ${{ vars.APP_DIRECTORY }} && git pull --rebase origin master"
        echo "Successfully pulled repo."

    - name: Restarting autoexpense webapp service
      run: |
        ssh ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} /app/scripts/restart.sh
        echo "Successfully restarted."

    - name: run tests
      env:
        GITHUB: 1
      run: uv run make test-deployment
