name: Makefile CI

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  build:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install uv
      run: pip install uv

    - name: run tests
      run: uv run make test

    - name: Configure SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_FOR_LINODE}}

    - name: Git Pull
      run: |
        cd ${{ github.workspace }}
        ssh-keyscan -t rsa ${{SSH_HOST}} >> ~/.ssh/known_hosts
        ssh ${{SSH_USER}}@{{$SSH_HOST}} "cd ${{APP_DIR}} pp && git pull origin master"
        echo "Successfully pulled repo."

    - name: deploy to linode
      run: |
        ssh $SSH_USER@$SSH_HOST rm -rf $APP_DIR
        ssh $SSH_USER@$SSH_HOST git clone git@github.com:dypabo/autoexpense3.git $APP_DIR
        ssh $SSH_USER@$SSH_HOST "cd $APP_DIR ; git checkout master ; git pull ;"
        # systemd
        ssh $SSH_USER@$SSH_HOST cp $APP_DIR/scripts/autoexpense_webapp.service /etc/systemd/system/
        ssh $SSH_USER@$SSH_HOST systemctl daemon-reload
        ssh $SSH_USER@$SSH_HOST systemctl enable autoexpense_webapp.service
        ssh $SSH_USER@$SSH_HOST systemctl restart autoexpense_webapp.service
