name: Makefile CI

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  build:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install uv
      run: pip install uv

    - name: run tests
      run: uv run make test

    - name: Configure SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_FOR_LINODE}}

    - name: Git Pull
      run: |
        cd ${{ github.workspace }}
        ssh-keyscan -t rsa 192.53.123.44 >> ~/.ssh/known_hosts
        ssh root@192.53.123.44 "cd /app/autoexpense3 && git pull origin master"
        echo "Successfully pulled repo."

    - name: deploy to linode
      run: uv run make deploy
