name: Makefile CI

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  build:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install uv
      run: pip install uv

    - name: run tests
      run: uv run make test

    - name: Configure SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_FOR_LINODE}}

    - name: Git Pull
      run: |
        cd ${{ github.workspace }}
        ssh-keyscan -t rsa 192.53.123.44 >> ~/.ssh/known_hosts
        ssh root@192.53.123.44 "cd /app && git pull origin master"
        echo "Successfully pulled repo."

    - name: deploy to linode
      run: |
        ssh root@192.53.123.44 rm -rf /app
        ssh root@192.53.123.44 git clone git@github.com:dypabo/autoexpense3.git /app
        ssh root@192.53.123.44 "cd /app ; git checkout master ; git pull ;"
        # systemd
        ssh root@192.53.123.44 cp /app/scripts/autoexpense_webapp.service /etc/systemd/system/
        ssh root@192.53.123.44 systemctl daemon-reload
        ssh root@192.53.123.44 systemctl enable autoexpense_webapp.service
        ssh root@192.53.123.44 systemctl restart autoexpense_webapp.service
